export const BINGO_ITEMS: string[] = [
  "Gets nerdsniped",
  "Crashes out over Anthropic",
  "Gets someone a job / to SF",
  '"Let me just show you this really quick" (30 min later)',
  "Rants about TypeScript edge cases",
  "Sponsor read",
  "Chat bullies him into something",
  "Technical difficulties / stream setup issues",
  "Forgets to take out tea bag",
  "Leaks his email or API key",
  "Goes on an extended skateboard tangent",
  'Goes "WHAT THE F***!?" at some company',
  "Hasn't had time to do his hair",
  "Falls in love with something a viewer built",
  'Does the "don\'t credit me, you did all the work" thing',
  "Gets trolled by his team",
  "Spends 20 min fixing a typo type checking would catch",
  "Starts building then pivots to a totally different project",
  "Writes 50 lines then finds a 1-line built-in that does it",
  "Forgets to save and wonders why nothing works",
  'Claims "this should just work" — it does not',
  "Deletes a function then rewrites the exact same one",
  "Starts refactoring live and immediately regrets it",
  "Goes on an unsolicited rant about Next.js / Vercel",
  "Flip-flops on a framework he previously praised",
  'Declares something "the future of web dev"',
  "Compares everything to the T3 Stack unprompted",
  "Takes a shot at Prisma (he's a Drizzle guy now)",
  "Crashes out over OpenAI / GPT pricing",
  "Rants about vibe coding or AI-generated code",
  "Chat spams LULW at something Theo did wrong",
  "Viewer drops a link and Theo derails the whole stream",
  "Chat convinces him to do something he refused 5 min ago",
  "Basic chat question turns into a 10-min teaching tangent",
  "Cat appears on stream",
  "Stands up at standing desk mid-stream for no reason",
  "Shows desktop with embarrassing number of tabs open",
  "Dr Pepper or energy drink on desk",
  "Stares blankly at the screen for 10+ seconds",
  "Takes a sip of tea, makes a face, forgets it exists",
  'Says "bro" or "bruh" 5+ times in one minute',
  "Laughs alone at his own joke while chat is silent",
  "Reviews a random indie project and roasts the UI",
  "Discovers a new tool and wants to rewrite everything",
  "Mentions Y Combinator / being a founder unprompted",
];
